### ISSUE TITLE
sync writes in Android

### ISSUE THREAD

**Issue by alokrajiv** [GillesC/cordova-plugin-nativestorage#1]
Noticed that you use apply() followed by callbackContext.
Would it be better to use commit() and then return the value, because if multiple threads or simultaneous writes come, apply() is async and not blocking. Also there is no provision for getting response whether the write is complete in the callback.

**Comment by GillesC** [comment]
Thanks for the valuable input! 
I'll put it to good use, and start immediately with adapting it in my plugin.

**Comment by alokrajiv** [comment]
don't mind doing the android part. So, if you don't mind add me as the assignee.

**Comment by GillesC** [comment]
I've done it already! ;)

**Comment by alokrajiv** [comment]
no worries... saw the change. it'll be great if you refer the commit while closing the issue as well, just in case for later bug tracking..

**Comment by GillesC** [comment]
Issue resolved in commit 5d6364b6b696a217a9fb4cf7f96b7b36e187ed70

(BTW I'm relatively new to the world of Github, thanks for helping me getting things done right.)

**Comment by alokrajiv** [comment]
no problem.
