### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by marianfeiler** [GillesC/cordova-plugin-nativestorage#10]
I installed the Plugin, but it is not working.
nativeStorage is not available.

I try on deviceready:

var ns = (typeof nativeStorage == "undefined") ? false : true;
if(ns)
{
    alert("nativeStorage is available");
    nativeStorage.putString(
        "foo",
        "bar",
        function(result)
        {
            alert(result);
         },
         function(e)
         {
            alert(e);
         }
    );
    nativeStorage.getString(
        "bla",
        function(result)
        {
            alert(result);
        },
        function(e)
        {
            alert(e);
        }
    );
}

any ideas? I am using phonegap actual

**Comment by alokrajiv** [comment]
which platform are you using?

**Comment by marianfeiler** [comment]
I am working on iOS 9.3.1

**Comment by alokrajiv** [comment]
I am able to run it on iOS v9.3 without any issues. 
could you run 
`cordova plugin ls` 
and confirm output of the above command to have:
`cordova-plugin-nativestorage 1.0.9 "NativeStorage"`.

**Comment by marianfeiler** [comment]
I confirm the output, see below:

```
iMac:mySprit marianfeiler$ sudo cordova plugin ls 
cordova-plugin-console 1.0.2 "Console"
cordova-plugin-nativestorage 1.0.9 "NativeStorage"
cordova-plugin-statusbar 1.0.1 "StatusBar"
```

**Comment by alokrajiv** [comment]
@marianfeiler  
I noticed you are using `typeof nativeStorage `
could you try with `typeof NativeStorage` with the first letter 'n' as capital 'N'.

**Comment by marianfeiler** [comment]
I tried, but i run in Error. 
But I tried and tried, and then, I think it was Build Error with Phonegap.
Now it works like a charm :)
But I think the handling could be nicer... like just so for setting:
`var result = nativeStorage.set("foo", "bar"); // returns true|false`
or for getting:
`var myString = nativeStorage.getString("foo"); // returns String (bar) and in error false`
Thanks again a lot for helping...

**Comment by alokrajiv** [comment]
Great to know you got it working.  So, thank you for confirming. I am closing this issue.
Also we don't have a return type, because the operation is asynchronous. 
So, for errors as-per Javascript standards, you could use the 4rd parameter of NativeStorage.set() to pass an error handler function, which will be called with the error as parameter.

**Comment by GillesC** [comment]
I've opted for callback functions because of the nature of JavaScript.  It's an inherent strategy used in JavaScript. It makes asynchronuous communication possible. Thus, not blocking the rest of the code. The overhead introduced by Cordova is in that manner less obvious.

**Comment by Neo1975** [comment]
Hi,
I had the same problem. After many test try and debugging I understand that: angular application, service and controller are initialized before cordova plugins. So in my case I use **NativeStorage** object at Service startup.
To avoid problems I suggest you to:

- Remove **ng-app** from body
- put this cose at the end of _index.html_

`<script type="text/javascript">
document.addEventListener('deviceready', function onDeviceReady() {
       angular.bootstrap(document.querySelector('body'), ['starter']);
}, false);
</script>`

Instead I would like to advice @GillesC to insert this instructions inside Readme file.

**Comment by GillesC** [comment]
@Neo1975 I've written a [wrapper ](https://github.com/TheCocoaProject/ngcordova-wrapper-nativestorage), can u see if the problem persists when using the wrapper to acces the NativeStorage functionalities. I so I will include your instructions for this problem in the README, otherwise the users should use the wrapper for using the plugin in Ionic or other AngulerJS related frameworks.

**Comment by Neo1975** [comment]
Indeed, I imported wrapper project as you describe in the ReadMe file: the
exception is throw by getItem and setItem method found NativeStorage
undefined. Perhaps can depends on Ionic Framework but in the way that I
describe above now works well.

Il giorno ven 27 mag 2016 alle ore 18:04 Gilles Callebaut <
notifications@github.com> ha scritto:

**Comment by GillesC** [comment]
@Neo1975 Thanks for your contribution, I will update the readme and will look further into the matter, when I have more time.

**Comment by jwuliger** [comment]
Hello. I know this is closed, but I am trying to use the fix described by @Neo1975. I am not able to get my angular app to run. Is there a more specific place that I place the javascript bootstrapper after I remove ng-app from my body tag? Thanks so much for any help.

**Comment by alokrajiv** [comment]
hi @jwuliger, not very familiar with the exact issue, but did you try to bootstrap after onready using the script as mentioned by @Neo1975.

**Comment by jwuliger** [comment]
Hello @alokrajiv Thanks for the reply. Yes, I am using the script as suggested, just changed the app name. I have tried placing it in many different locations at the bottom of my index.html file. Here is a snippet:

```
	/// all my angular/ionic & app js is above ///
	<script src="lib/ngcordova-wrapper-nativestorage/dist/ngcordova-wrapper-nativestorage.min.js"></script>
</head>

<body> <!--ng-app="app"-->
	<ion-nav-view></ion-nav-view>
</body>
	<script type="text/javascript">
		document.addEventListener("deviceready", function onDeviceReady() {
			angular.bootstrap(document.querySelector("body"), ["app"]);
		}, false);
	</script>
</html>
```

I suppose this was the solution to getting "undefined" when using a get call when there is nothing in storage yet. Like I said I have tried many iterations of the code placement. Maybe I something else in the wrong place. Thanks for your help!

**Comment by alokrajiv** [comment]
@jwuliger Which version of angular are you using? also are you using ionic? without ionic I am able to inject `$cordovaNativeStorage` without any troubles using ng-app itself, no bootstrapping.
