### ISSUE TITLE
Release tagging.

### ISSUE THREAD

**Issue by alokrajiv** [GillesC/cordova-plugin-nativestorage#11]
@GillesC What do you say we start release tagging to maintain version binaries on github itself.

**Comment by GillesC** [comment]
To be able to break with the current API in the future?
Or for another purpose?

**Comment by alokrajiv** [comment]
Not necessarily, but mainly to maintain downloading binaries if anyone requires. And for keeping track of release commits, versions and for users to easily differentiate between development builds and production builds.
[Github Spec](https://help.github.com/articles/creating-releases/)

**Comment by GillesC** [comment]
I shall maintain release tagging. These releases will follow the same version numbers as the npm registery, which can be found in the plugin.xml

**Comment by alokrajiv** [comment]
Shall I add a release tag for the current version for now, or you will do it ?

**Comment by GillesC** [comment]
I'm currently in class, so it would be nice if you did the current one ;)

**Comment by alokrajiv** [comment]
No problem.

**Comment by alokrajiv** [comment]
@GillesC  Done. I have added v1.0.10 release tag on current build. 
NPM Registry is one version now behind. I have not updated that because I'm not marked as a collaborator there.

**Comment by GillesC** [comment]
@alokrajiv I've justed completed the publish ;)

**Comment by alokrajiv** [comment]
Perfect.
