### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by thedoorbell** [GillesC/cordova-plugin-nativestorage#13]
When I launch my app in console I get "Uncaught ReferenceError: require is not defined" from NativeStorage.js.

And when I try to set, for example, string I get "Uncaught TypeError: NativeStorage.putString is not a function".

What should I do?

**Comment by alokrajiv** [comment]
What platform are you running?

**Comment by thedoorbell** [comment]
Im using Ionic framework and testing in Chrome both iOS and Android.

**Comment by alokrajiv** [comment]
You are testing Chrome, meaning using `ionic serve` or `cordova run browser`?

**Comment by thedoorbell** [comment]
ionic serve

**Comment by alokrajiv** [comment]
Ionic is facing an issue with serve [see link](https://github.com/driftyco/ionic-cli/issues/354).
So, plugins don't work in ionic serve and the error you are getting is not a plugin error, but a cordova error because require is included from cordova and it itself isn't available.

**Comment by thedoorbell** [comment]
So If I tried to test in Ionic View it should works?

**Comment by alokrajiv** [comment]
do 
```
cordova platform add browser
cordova run browser
```

Use Ripple emulator from there if required.

**Comment by thedoorbell** [comment]
`Error executing "google-chrome --user-data-dir=/tmp/temp_chrome_user_data_dir_for_cordova http://localhost:8000/index.html": /bin/sh: 1: google-chrome: not found
`

**Comment by alokrajiv** [comment]
I will continue to try and help you, but since this isn't a NativeStorage issue, I'm closing the issue.

**Comment by alokrajiv** [comment]
I looks like google-chrome is not installed or configured rite. What Operating system are you using?

**Comment by thedoorbell** [comment]
Oh right. Im developing in VirtualBox Debian without UI, and when I running ionic serve, im testing from browser in Windows...

**Comment by alokrajiv** [comment]
is your issue resolved?

**Comment by thedoorbell** [comment]
No.

**Comment by alokrajiv** [comment]
you cannot run it as a server, because cordova.js has to be served from the platform. try testing on an emulator or device.

**Comment by thedoorbell** [comment]
Okay, thanks, now I got it :)

**Comment by pankajdx48** [comment]
what my understanding is require is node js methode how i can integrate node js code in ionic

**Comment by GillesC** [comment]
@pankajdx48 check out [our documentation for using Ionic and other platforms](https://github.com/TheCocoaProject/cordova-plugin-nativestorage#supported_frameworks).
