### ISSUE TITLE
Demo Examples

### ISSUE THREAD

**Issue by alokrajiv** [GillesC/cordova-plugin-nativestorage#16]
Add an example demo

**Comment by alokrajiv** [comment]
@GillesC  I'm making a pull request with a full working example. But, could you add documentation for it on the ReadMe.

**Comment by GillesC** [comment]
@alokrajiv I will! ;)

**Comment by alokrajiv** [comment]
Closing with commit 88d77bf0f89bdd437214ce5131c3863114e73dab

**Comment by alokrajiv** [comment]
@GillesC 

> git clone https://github.com/alokrajiv/cordova-plugin-nativestorage.git
> cd cordova-plugin-nativestorage/examples/demo/
> cordova platform add ios
> cordova plugin add cordova-plugin-nativestorage
> cordova plugin add http://git-wip-us.apache.org/repos/asf/cordova-plugin-test-framework.git
> cordova plugin add https://github.com/GillesC/cordova-plugin-nativestorage.git#:/tests
> cordova emulate ios
