### ISSUE TITLE
Object datatype support

### ISSUE THREAD

**Issue by alokrajiv** [GillesC/cordova-plugin-nativestorage#4]
would it be good to have put and get for object datatypes as well.

**Comment by alokrajiv** [comment]
For my purpose now, I am stringify-ing the object and using the string put/get functions. But, I'd like add it to the plugin as a function.

**Comment by alokrajiv** [comment]
I have made a merge request with the same.

**Comment by GillesC** [comment]
And how are you parsing the string back to an object? Are you using JSON or something?
I don't see how you're doing it at the moment.

**Comment by alokrajiv** [comment]
line-no: 144 & 156 in NativeStorage.js

**Comment by GillesC** [comment]
Aah I see indeed, storing it as a JSON string.

**Comment by GillesC** [comment]
Thanks for the input. I will update the readme file and the npm registry

**Comment by alokrajiv** [comment]
Closed with commit  [e0e8b0b] (https://github.com/GillesC/cordova-plugin-nativestorage/commit/e0e8b0bd6dcf7122fe98e144008b38f419fea728) .

**Comment by alokrajiv** [comment]
@GillesC  I think this plugin would be very useful if made more popular. I am interested in joining as collaborator on this repo.

**Comment by GillesC** [comment]
479 downloads in less than 3 weeks isn't nothing, but ey. 
What enhancements would you make?

**Comment by GillesC** [comment]
Still losed with commit e0e8b0bd6dcf7122fe98e144008b38f419fea728.
I just pressed the wrong button --'

**Comment by alokrajiv** [comment]
@GillesC for now I was thinking of integrating cordova-test framework which is very standard in most standard cordova plugins like `media` , `device` ... And then also integrate travis for build test. Other features depending on feature requests maybe.

**Comment by GillesC** [comment]
@alokrajiv You're now officially a collab ;) Congratz.

**Comment by alokrajiv** [comment]
@GillesC thanks, what is ur email. I wanted to remove these off-topic conversations from this issue to mail thread.
