### ISSUE TITLE
Travis CI Integration

### ISSUE THREAD

**Issue by alokrajiv** [GillesC/cordova-plugin-nativestorage#6]
Integrate Travis CI for the current npm test.

**Comment by alokrajiv** [comment]
@GillesC  since `npm test` is set up, enable TRAVIS CI.

**Comment by GillesC** [comment]
@alokrajiv Added TRAVIS CI to this repo, will you indclude the `.travis.yml` file?
I'm new to this kind of testing (I'm a Java-guy)

**Comment by alokrajiv** [comment]
No problem I'll look into it.

**Comment by GillesC** [comment]
And passed! 
`.travis.yml ` added in commit 1bc2789961ddcf0c497078c886c51462cda8d1c6

**Comment by alokrajiv** [comment]
cud you add the badge on the readme page also.

**Comment by GillesC** [comment]
Done.

**Comment by alokrajiv** [comment]
perfect.
Added travis badge in commit : [5d54f80](https://github.com/GillesC/cordova-plugin-nativestorage/commit/5d54f806a351ce4990a16450ac7fb06048cbdf69)
