### ISSUE TITLE
Uniform defaults for getter functions.

### ISSUE THREAD

**Issue by alokrajiv** [GillesC/cordova-plugin-nativestorage#8]
Should default values be uniform across platforms, because currently defaults are different depending on the platform.

**Comment by GillesC** [comment]
I've opted for logical default values in Android. But iOS (NSUSerDefaults) uses its own default values which could not be (by my knowledge) modified.

I've chosen not to take the same defaults because the default values in NSUSerDefaults were not --by my opnion-- straightforward.

**Comment by alokrajiv** [comment]
ok.. I asked this because when using the plugin from within the app the javascript code logic might need to be aware which platform it is currently running in for decision making.
Example:
> NativeStorage.getInt("ref_obj", function(result) {
>     if (device.platform == "iOS") {
>         if (result == -1)
>             alert('no existing value');
>     }
>     else if (device.platform == "Android") {
>         if (result == 0)
>             alert('no existing value');
>     }
> 
> },
>     function(e) {
>         console.log(e);
>     });

This requires cordova-device plugin. 

If we enforce W3C javascript standard defaults from our `NativeStorage.js` then the plugin functions' operation will be true cross-platform behaving uniformly across devices. But if you think we are breaking some standard, then we will leave it as it is and close the issue.

**Comment by GillesC** [comment]
I could change the default values in Android, to the corresponding values in iOS. If you think this is the way to go. I'm just thinking of the trade-off here. Cross-platform behaviour or logical defaults values in Android. a default '0' value for integers is just ridiculous. But if you --with your experience-- think that we should change this, by all means. ;)

**Comment by alokrajiv** [comment]
lets leave it open for opinions from other users and decide based on the outcome.

**Comment by GillesC** [comment]
This approach will be adressed in the new version (2.0.0).
There will be no need to specifiy default values, because when the requested value isn't accessible the error-callback will be invoked.

More info soon.

**Comment by GillesC** [comment]
This issue is no longer relevant because of the newly API. 
For more information check the documentation and wiki page
Solved in commit 08660e93dba9f52769c6584ee8884f0e85bc40a0 (merge)
